import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { VscTwitter } from "react-icons/vsc";
import { GoHome } from "react-icons/go";
import { BsEnvelope } from "react-icons/bs";
import { BiHash } from "react-icons/bi";
import { BsBell } from "react-icons/bs";
import { FiBookmark } from "react-icons/fi";
import { RiFileList2Line } from "react-icons/ri";
import { FaRegUser } from "react-icons/fa";
import { CgMoreO } from "react-icons/cg";
import { BsStars } from "react-icons/bs";
import { HiOutlinePhotograph } from "react-icons/hi";
import { RiFileGifLine } from "react-icons/ri";
import { BiPoll } from "react-icons/bi";
import { BsEmojiSmile } from "react-icons/bs";
import { AiOutlineSchedule } from "react-icons/ai";
import { HiOutlineLocationMarker } from "react-icons/hi";
import { RiChat1Line } from "react-icons/ri";
import { FaRetweet } from "react-icons/fa";
import { AiOutlineHeart } from "react-icons/ai";
import { FiShare } from "react-icons/fi";
import { BsSearch } from "react-icons/bs";
import { FaFeatherAlt } from "react-icons/fa";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container">
        <div className="content flex">
          {/* left */}
          <div className="flex flex-col left justify-start">
            <a href="#" className="text-white logo p-3 text-3xl">
              <VscTwitter />
            </a>
            <a
              className="text-white flex align-middle py-3 pl-3 pr-4 my-1"
              href="#"
            >
              <GoHome className="mr-5 text-2xl" />
              <p className="text-xl font-bold ">Home</p>
            </a>
            <a
              className="text-white flex align-middle py-3 pl-3 pr-4 my-1"
              href="#"
            >
              <BiHash className="mr-5 text-2xl" />

              <p className="text-xl "> Explore</p>
            </a>
            <a
              className="text-white flex align-middle py-3 pl-3 pr-4 my-1"
              href="#"
            >
              <BsBell className="mr-5 text-2xl" />

              <p className="text-xl ">Notifications</p>
            </a>
            <a
              className="text-white flex align-middle py-3 pl-3 pr-4 my-1"
              href="#"
            >
              <BsEnvelope className="mr-5 text-2xl" />

              <p className="text-xl "> Messages</p>
            </a>
            <a
              className="text-white flex align-middle py-3 pl-3 pr-4 my-1"
              href="#"
            >
              <FiBookmark className="mr-5 text-2xl" />

              <p className="text-xl "> Bookmarks</p>
            </a>
            <a
              className="text-white flex align-middle py-3 pl-3 pr-4 my-1"
              href="#"
            >
              <RiFileList2Line className="mr-5 text-2xl" />

              <p className="text-xl ">Lists</p>
            </a>
            <a
              className="text-white flex align-middle py-3 pl-3 pr-4 my-1"
              href="#"
            >
              <FaRegUser className="mr-5 text-2xl" />

              <p className="text-xl "> Profile</p>
            </a>
            <a
              className="text-white flex align-middle py-3 pl-3 pr-4 my-1"
              href="#"
            >
              <CgMoreO className="mr-5 text-2xl" />

              <p className="text-xl ">More</p>
            </a>
            <a
              className="text-white text-xl font-bold text-center lg:px-24 px-10 py-4 tweet mt-4"
              href="#"
            >
              Tweet
            </a>
            <a
              href="#"
              className="py-1 px-1 mb-1 md-tweet m-auto text-xl text-white lg:hidden block twet"
            >
              <FaFeatherAlt />
            </a>
            <div className="mt-auto">
              <a href="#" className="mt-auto align-bottom flex py-3 pl-3 pr-4">
                <img
                  src="/a.jpg"
                  className=" lg:w-12 lg:h-12 h-9 w-9 rounded-full mr-3"
                  alt="me"
                />
                <div className="flex flex-col">
                  <p className=" text-white font-bold pb-0 mb-0">
                    Dev Ahmad Nagm
                  </p>
                  <p className=" text-gray-500 pt-0 mt-0">@DevAhmdNagm</p>
                </div>
                <p className="text-white ml-5 lg:text-2xl tex-lg ">...</p>
              </a>
            </div>
          </div>
          {/* center */}
          <div className="contentCenter">
            <div className="flex flex-col">
              <div className="top flex justify-between items-center pl-4 pt-2 pr-2">
                <a href="#">
                  <p className="font-bold text-xl text-white">Home</p>
                </a>
                <a href="#" className="icn p-2">
                  <p>
                    <BsStars className="text-white text-xl" />
                  </p>
                </a>
              </div>
              <div className="midle flex items-center">
                <img
                  src="/a.jpg"
                  className=" lg:w-12 lg:h-12 w-9 h-9 rounded-full ml-4 mr-1 my-2"
                  alt="me"
                />
                <input
                  type="text"
                  className="bg-transparent ml-2 mt-3 text-gray-400 text-xl outline-none"
                  placeholder="What's Happening?"
                />
              </div>
              <div className="botm flex lg:justify-between justify-center items-center lg:p-4">
                <div className="icons flex lg:ml-14">
                  <a href="#" className="icn p-2">
                    <HiOutlinePhotograph className="text-white t" />
                  </a>
                  <a href="#" className="icn p-2">
                    <RiFileGifLine className="text-white t" />
                  </a>
                  <a href="#" className="icn p-2">
                    <BiPoll className="text-white t" />
                  </a>
                  <a href="#" className="icn p-2">
                    <BsEmojiSmile className="text-white t" />
                  </a>
                  <a href="#" className="icn p-2">
                    <AiOutlineSchedule className="t" />
                  </a>
                  <a href="#" className="icn p-2">
                    <HiOutlineLocationMarker className="t" />
                  </a>
                </div>
                <a
                  href="#"
                  className="py-2 px-4 text-white font-bold mr-4 lg:block hidden twet"
                >
                  Tweet
                </a>
                <a
                  href="#"
                  className="py-1 px-1 mb-1  text-white lg:hidden block twet"
                >
                  <FaFeatherAlt />
                </a>
              </div>
              <div className="showmore">
                <a href="#">
                  <p className=" text-center text-md py-4 clr">
                    Show 81 tweets
                  </p>
                </a>
              </div>
              <div className="post">
                <div className="flex px-3 pt-3 items-top">
                  <img
                    src="/6R0-p1Vf_400x400.jpg"
                    className=" w-12 rounded-full mr-3"
                    alt="next"
                  />
                  <div className="flex flex-col">
                    <div className="flex mt-1 items-center">
                      <p className="text-white font-bold pr-2">Vercel</p>
                      <img
                        src="/Twitter.png"
                        className=" w-4 h-4 rounded-full mr-2"
                        alt="twtr"
                      />
                      <p className=" text-slate-500">@Vercel . 9m</p>
                    </div>
                    👩‍💻
                  </div>
                </div>
                <div className="postbody pl-16 pr-6">
                  <p className="text-white text-xl mb-2 pl-2">
                    Turborepo works with JavaScript and TypeScript monorepos.
                  </p>
                  <p className="text-white text-xl mb-3 pl-2">
                    Monorepos are codebases containing multiple projects, often
                    using multiple frameworks, in a single unified code
                    repository.
                  </p>
                  <img
                    src="/FGKrFLcWYAYP1ZJ.jpg"
                    className=" rounded-2xl border-slate-700 border ml-2"
                    alt="post"
                  />
                  {/* <p className=" text-slate-500 py-3">
                    3:33 PM · Dec 9, 2021·Twitter Web App
                  </p> */}
                  <div className="inter py-3 flex justify-between pl-2">
                    <a href="#" className="pl-2 flex items-center">
                      <RiChat1Line className="text-gray-500 text-xl" />
                      <p className="text-gray-500 pl-4">1k</p>
                    </a>
                    <a href="#" className=" flex items-center">
                      <FaRetweet className="text-gray-500 text-xl" />
                      <p className="text-gray-500 pl-4">865</p>
                    </a>
                    <a href="#" className="pl-2 flex items-center">
                      <AiOutlineHeart className="text-gray-500 text-xl" />
                      <p className="text-gray-500 pl-4">3k</p>
                    </a>
                    <a href="#" className="pr-20 flex items-center">
                      <FiShare className="text-gray-500 text-xl" />
                    </a>
                  </div>
                </div>
              </div>
              <div className="post">
                <div className="flex px-3 pt-3 items-top">
                  <img
                    src="/6R0-p1Vf_400x400.jpg"
                    className=" w-12 rounded-full mr-3"
                    alt="next"
                  />
                  <div className="flex flex-col">
                    <div className="flex mt-1 items-center">
                      <p className="text-white font-bold pr-2">Vercel</p>
                      <img
                        src="/Twitter.png"
                        className=" w-4 h-4 rounded-full mr-2"
                        alt="twtr"
                      />
                      <p className=" text-slate-500">@Vercel . 9m</p>
                    </div>
                    👩‍💻
                  </div>
                </div>
                <div className="postbody pl-16 pr-6">
                  <p className="text-white text-xl mb-2 pl-2">
                    Turborepo works with JavaScript and TypeScript monorepos.
                  </p>
                  <p className="text-white text-xl mb-3 pl-2">
                    Monorepos are codebases containing multiple projects, often
                    using multiple frameworks, in a single unified code
                    repository.
                  </p>
                  <img
                    src="/FGKrFLcWYAYP1ZJ.jpg"
                    className=" rounded-2xl border-slate-700 border ml-2"
                    alt="post"
                  />
                  {/* <p className=" text-slate-500 py-3">
                    3:33 PM · Dec 9, 2021·Twitter Web App
                  </p> */}
                  <div className="inter py-3 flex justify-between pl-2">
                    <a href="#" className="md:pl-2 flex items-center">
                      <RiChat1Line className="text-gray-500 text-xl" />
                      <p className="text-gray-500 md:pl-4">1k</p>
                    </a>
                    <a href="#" className=" flex items-center">
                      <FaRetweet className="text-gray-500 text-xl" />
                      <p className="text-gray-500 md:pl-4">865</p>
                    </a>
                    <a href="#" className="pl-2 flex items-center">
                      <AiOutlineHeart className="text-gray-500 text-xl" />
                      <p className="text-gray-500 md:pl-4">3k</p>
                    </a>
                    <a href="#" className="pr-20 flex items-center">
                      <FiShare className="text-gray-500 text-xl" />
                    </a>
                  </div>
                </div>
              </div>
              <div className="post">
                <div className="flex px-3 pt-3 items-top">
                  <img
                    src="/6R0-p1Vf_400x400.jpg"
                    className=" w-12 rounded-full mr-3"
                    alt="next"
                  />
                  <div className="flex flex-col">
                    <div className="flex mt-1 items-center">
                      <p className="text-white font-bold pr-2">Vercel</p>
                      <img
                        src="/Twitter.png"
                        className=" w-4 h-4 rounded-full mr-2"
                        alt="twtr"
                      />
                      <p className=" text-slate-500">@Vercel . 9m</p>
                    </div>
                    👩‍💻
                  </div>
                </div>
                <div className="postbody pl-16 pr-6">
                  <p className="text-white text-xl mb-2 pl-2">
                    Turborepo works with JavaScript and TypeScript monorepos.
                  </p>
                  <p className="text-white text-xl mb-3 pl-2">
                    Monorepos are codebases containing multiple projects, often
                    using multiple frameworks, in a single unified code
                    repository.
                  </p>
                  <img
                    src="/FGKrFLcWYAYP1ZJ.jpg"
                    className=" rounded-2xl border-slate-700 border ml-2"
                    alt="post"
                  />
                  {/* <p className=" text-slate-500 py-3">
                    3:33 PM · Dec 9, 2021·Twitter Web App
                  </p> */}
                  <div className="inter py-3 flex justify-between pl-2">
                    <a href="#" className="pl-2 flex items-center">
                      <RiChat1Line className="text-gray-500 text-xl" />
                      <p className="text-gray-500 pl-4">1k</p>
                    </a>
                    <a href="#" className=" flex items-center">
                      <FaRetweet className="text-gray-500 text-xl" />
                      <p className="text-gray-500 pl-4">865</p>
                    </a>
                    <a href="#" className="pl-2 flex items-center">
                      <AiOutlineHeart className="text-gray-500 text-xl" />
                      <p className="text-gray-500 pl-4">3k</p>
                    </a>
                    <a href="#" className="pr-20 flex items-center">
                      <FiShare className="text-gray-500 text-xl" />
                    </a>
                  </div>
                </div>
              </div>
              <div className="post">
                <div className="flex px-3 pt-3 items-top">
                  <img
                    src="/6R0-p1Vf_400x400.jpg"
                    className=" w-12 rounded-full mr-3"
                    alt="next"
                  />
                  <div className="flex flex-col">
                    <div className="flex mt-1 items-center">
                      <p className="text-white font-bold pr-2">Vercel</p>
                      <img
                        src="/Twitter.png"
                        className=" w-4 h-4 rounded-full mr-2"
                        alt="twtr"
                      />
                      <p className=" text-slate-500">@Vercel . 9m</p>
                    </div>
                    👩‍💻
                  </div>
                </div>
                <div className="postbody pl-16 pr-6">
                  <p className="text-white text-xl mb-2 pl-2">
                    Turborepo works with JavaScript and TypeScript monorepos.
                  </p>
                  <p className="text-white text-xl mb-3 pl-2">
                    Monorepos are codebases containing multiple projects, often
                    using multiple frameworks, in a single unified code
                    repository.
                  </p>
                  <img
                    src="/FGKrFLcWYAYP1ZJ.jpg"
                    className=" rounded-2xl border-slate-700 border ml-2"
                    alt="post"
                  />
                  {/* <p className=" text-slate-500 py-3">
                    3:33 PM · Dec 9, 2021·Twitter Web App
                  </p> */}
                  <div className="inter py-3 flex justify-between pl-2">
                    <a href="#" className="pl-2 flex items-center">
                      <RiChat1Line className="text-gray-500 text-xl" />
                      <p className="text-gray-500 pl-4">1k</p>
                    </a>
                    <a href="#" className=" flex items-center">
                      <FaRetweet className="text-gray-500 text-xl" />
                      <p className="text-gray-500 pl-4">865</p>
                    </a>
                    <a href="#" className="pl-2 flex items-center">
                      <AiOutlineHeart className="text-gray-500 text-xl" />
                      <p className="text-gray-500 pl-4">3k</p>
                    </a>
                    <a href="#" className="pr-20 flex items-center">
                      <FiShare className="text-gray-500 text-xl" />
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {/* right */}
          <div className="right flex flex-col pb-4 pt-2 px-6">
            <div className="search flex items-center px-6 py-1">
              <BsSearch className="text-gray-400" />
              <input
                type="search"
                className=" bg-transparent px-4 py-2 ml-3 text-gray-500 outline-none"
                name="search here"
                id="search"
                placeholder="Search Twitter"
              />
            </div>
            <div className="rightpost flex flex-col py-4 mt-4">
              <p className="text-white text-xl pb-2 px-4">
                What&apos;s Happening
              </p>

              <div className="rightcon flex py-3 px-4">
                <a href="#" className="flex">
                  <div className="flex flex-col">
                    <p className="text-gray-600">Football · Last night</p>
                    <p className="text-white text-lg">
                      Supporting the Future of Next Js
                    </p>
                  </div>
                  <img
                    src="/6R0-p1Vf_400x400.jpg"
                    className=" w-20 h-20 rounded-2xl"
                    alt="pic"
                  />
                </a>
              </div>
              <div className="rightcon flex py-3 px-4">
                <a href="#" className="flex">
                  <div className="flex flex-col">
                    <p className="text-gray-600">Trending In Egypt </p>
                    <p className="text-white text-lg">
                      #AhmadNagm_must _work_at_google
                    </p>
                    <p className="text-gray-600">100k Tweets</p>
                  </div>
                </a>
              </div>

              <div className="rightcon flex py-3 px-4">
                <a href="#" className="flex">
                  <div className="flex flex-col">
                    <p className="text-gray-600">Football · Last night</p>
                    <p className="text-white text-lg">
                      Supporting the Future of Next Js
                    </p>
                  </div>
                  <img
                    src="/6R0-p1Vf_400x400.jpg"
                    className=" w-20 h-20 rounded-2xl"
                    alt="pic"
                  />
                </a>
              </div>

              <div className="rightcon flex py-3 px-4">
                <a href="#" className="flex">
                  <div className="flex flex-col">
                    <p className="text-gray-600">Football · Last night</p>
                    <p className="text-white text-lg">
                      Supporting the Future of Next Js
                    </p>
                  </div>
                  <img
                    src="/6R0-p1Vf_400x400.jpg"
                    className=" w-20 h-20 rounded-2xl"
                    alt="pic"
                  />
                </a>
              </div>
              <div className="rightcon p-4 sho">
                <a href="#">show more</a>
              </div>
            </div>
            <div className="rightpost flex flex-col py-4 mt-4">
              <p className="text-white text-xl pb-2 px-4 mb-2">Who to follow</p>
              <div className="rightcon flex px-4 py-2">
                <a href="#" className="flex items-center w-full">
                  <img
                    src="/6R0-p1Vf_400x400.jpg"
                    className=" w-14 h-14 rounded-full"
                    alt="pic"
                  />
                  <div className="flex flex-col pl-2">
                    <p className="text-white text-lg font-bold ">vercel</p>
                    <p className="text-gray-500">@vercel</p>
                  </div>
                  <a href="#" className="follow font-bold ml-auto">
                    follow
                  </a>
                </a>
              </div>
              <div className="rightcon flex px-4 py-2">
                <a href="#" className="flex items-center w-full">
                  <img
                    src="/6R0-p1Vf_400x400.jpg"
                    className=" w-14 h-14 rounded-full"
                    alt="pic"
                  />
                  <div className="flex flex-col pl-2">
                    <p className="text-white text-lg font-bold ">vercel</p>
                    <p className="text-gray-500">@vercel</p>
                  </div>
                  <a href="#" className="follow font-bold ml-auto">
                    follow
                  </a>
                </a>
              </div>
              <div className="rightcon p-4 sho">
                <a href="#">show more</a>
              </div>
            </div>
            <p className="copy pt-2 text-gray-500">
              Terms of Service Privacy info More © 2022 Twitter, Inc.
            </p>
          </div>
        </div>
      </main>
    </>
  );
}
